name: Internal Release

on:
  push:
    branches:
      - main

jobs:
  update-draft-release:
    runs-on: macos-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  submit-release:
    runs-on: macos-latest
    needs: [ update-draft-release ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Generate build number
        run: echo "BUILD_NUMBER=${{github.run_number}}" > app/build_number.properties

      - name: Create API keys properties file
        run: |
          mkdir -p release
          echo "${{ secrets.API_KEYS_PROPERTIES }}" > release/api-keys.properties

      - name: Create google services file
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo "$GOOGLE_SERVICES" | base64 -D > app/google-services.json

      - name: Create google play key file
        env:
          GOOGLE_PLAY: ${{ secrets.GOOGLE_PLAY }}
        run: |
          mkdir -p distribution
          echo "$GOOGLE_PLAY" | base64 -D > distribution/play-key.json

      - name: Create keystore props file
        env:
          KEYSTORE_PROPS: ${{ secrets.KEYSTORE_PROPS }}
        run: echo "$KEYSTORE_PROPS" > release/keystore.properties

      - name: Create keystore file
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: echo "$KEYSTORE" | base64 -D > release/sdah_key.jks

      - name: Build Release
        run: ./gradlew app:bundleRelease --stacktrace

      - name: Publish to Alpha track
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: distribution/play-key.json
          packageName: com.tinashe.sdah
          track: internal
          status: completed
          whatsNewDirectory: distribution/whatsnew
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          mappingFile: app/build/outputs/mapping/release/mapping.txt
